package day1;

public class BankAcc {
	String AccHolderName;
	long AccNumber;
	double Balance;
	static String BankName;

	public static void main(String[] args) {
		BankAcc Obj1 = new BankAcc();
		Obj1.AccHolderName = "Ram";
		Obj1.AccNumber = 1234567890l;
		Obj1.Balance = 68000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj1.AccHolderName);
		System.out.println("Account Number :" + Obj1.AccNumber);
		System.out.println("Balance :" + Obj1.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj2 = new BankAcc();
		Obj2.AccHolderName = "Tam";
		Obj2.AccNumber = 8234567890l;
		Obj2.Balance = 98000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj2.AccHolderName);
		System.out.println("Account Number :" + Obj2.AccNumber);
		System.out.println("Balance :" + Obj2.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj3 = new BankAcc();
		Obj3.AccHolderName = "Jam";
		Obj3.AccNumber = 7234567890l;
		Obj3.Balance = 38000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj3.AccHolderName);
		System.out.println("Account Number :" + Obj3.AccNumber);
		System.out.println("Balance :" + Obj3.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj4 = new BankAcc();
		Obj4.AccHolderName = "Sam";
		Obj4.AccNumber = 9234567890l;
		Obj4.Balance = 78000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj4.AccHolderName);
		System.out.println("Account Number :" + Obj4.AccNumber);
		System.out.println("Balance :" + Obj4.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj5 = new BankAcc();
		Obj5.AccHolderName = "Oam";
		Obj5.AccNumber = 5234567890l;
		Obj5.Balance = 8000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj5.AccHolderName);
		System.out.println("Account Number :" + Obj5.AccNumber);
		System.out.println("Balance :" + Obj5.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj6 = new BankAcc();
		Obj6.AccHolderName = "Tom";
		Obj6.AccNumber = 6234567890l;
		Obj6.Balance = 69000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj6.AccHolderName);
		System.out.println("Account Number :" + Obj6.AccNumber);
		System.out.println("Balance :" + Obj6.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj7 = new BankAcc();
		Obj7.AccHolderName = "Scoot";
		Obj7.AccNumber = 8234567890l;
		Obj7.Balance = 6600;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj7.AccHolderName);
		System.out.println("Account Number :" + Obj7.AccNumber);
		System.out.println("Balance :" + Obj7.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj8 = new BankAcc();
		Obj8.AccHolderName = "Smith";
		Obj8.AccNumber = 936234567890l;
		Obj8.Balance = 68200;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj8.AccHolderName);
		System.out.println("Account Number :" + Obj8.AccNumber);
		System.out.println("Balance :" + Obj8.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj9 = new BankAcc();
		Obj9.AccHolderName = "Rocky";
		Obj9.AccNumber = 78234567890l;
		Obj9.Balance = 98000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj9.AccHolderName);
		System.out.println("Account Number :" + Obj9.AccNumber);
		System.out.println("Balance :" + Obj9.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
		System.out.println("------------------------------------------------------------");
		BankAcc Obj10 = new BankAcc();
		Obj10.AccHolderName = "Allen";
		Obj10.AccNumber = 958234567890l;
		Obj10.Balance = 63000;
		BankName = "ABC Bank";
		System.out.println("Account Holder Name :" + Obj10.AccHolderName);
		System.out.println("Account Number :" + Obj10.AccNumber);
		System.out.println("Balance :" + Obj10.Balance);
		System.out.println("BankName :" + BankAcc.BankName);
	}
}
